name: Continuous Integration

on:
  push:
    branches:
    - "ready/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{secrets.MICROSERVICE_WORKSHOP_TOBIAS}}

    - name: Compile
      run: mvn install
